/**
 * VACFA Translate — Demo Data
 * 
 * Mock data used across all prototype screens.
 * This simulates what would come from a real backend.
 */

import type {
  Language,
  Session,
  GlossaryTerm,
  CaptionEntry,
  TranslationChannel,
  DashboardStats,
  ActivityEntry,
  NavItem,
} from './types';

/** Supported languages in the VACFA Translate platform */
export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English', listenerCount: 0 },
  { code: 'fr', name: 'French', nativeName: 'Français', listenerCount: 0 },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', listenerCount: 0 },
  { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili', listenerCount: 0 },
  { code: 'yo', name: 'Yoruba', nativeName: 'Yorùbá', listenerCount: 0 },
  { code: 'zu', name: 'Zulu', nativeName: 'isiZulu', listenerCount: 0 },
  { code: 'am', name: 'Amharic', nativeName: 'አማርኛ', listenerCount: 0 },
  { code: 'ha', name: 'Hausa', nativeName: 'Hausa', listenerCount: 0 },
  { code: 'wo', name: 'Wolof', nativeName: 'Wolof', listenerCount: 0 },
  { code: 'ln', name: 'Lingala', nativeName: 'Lingála', listenerCount: 0 },
];

/** Mock sessions for the dashboard */
export const SESSIONS: Session[] = [
  {
    id: 'session-001',
    name: 'GAVI Immunization Summit 2026',
    organiser: 'Dr. Amina Osei',
    date: '2026-08-15',
    time: '09:00',
    sessionCode: '482916',
    languages: [LANGUAGES[0], LANGUAGES[1], LANGUAGES[2], LANGUAGES[3]],
    status: 'live',
    delegateCount: 347,
    description: 'Annual summit discussing immunization strategies across Sub-Saharan Africa.',
  },
  {
    id: 'session-002',
    name: 'Cold Chain Logistics Workshop',
    organiser: 'Prof. Kwame Asante',
    date: '2026-08-16',
    time: '14:00',
    sessionCode: '731058',
    languages: [LANGUAGES[0], LANGUAGES[1], LANGUAGES[4]],
    status: 'upcoming',
    delegateCount: 0,
    description: 'Workshop on maintaining cold chain integrity in tropical climates.',
  },
  {
    id: 'session-003',
    name: 'mRNA Vaccine Rollout: Lessons from Africa',
    organiser: 'Dr. Fatima Diallo',
    date: '2026-08-14',
    time: '10:00',
    sessionCode: '295647',
    languages: [LANGUAGES[0], LANGUAGES[1], LANGUAGES[2]],
    status: 'ended',
    delegateCount: 218,
    description: 'Review of mRNA vaccine deployment challenges and successes across the continent.',
  },
  {
    id: 'session-004',
    name: 'NITAG Strengthening Forum',
    organiser: 'Dr. Amina Osei',
    date: '2026-08-20',
    time: '11:00',
    sessionCode: '618243',
    languages: [LANGUAGES[0], LANGUAGES[1], LANGUAGES[3], LANGUAGES[6]],
    status: 'upcoming',
    delegateCount: 0,
    description: 'Forum on strengthening National Immunization Technical Advisory Groups across Africa.',
  },
  {
    id: 'session-005',
    name: 'Pharmacovigilance Best Practices',
    organiser: 'Prof. Kwame Asante',
    date: '2026-08-22',
    time: '15:00',
    sessionCode: '504791',
    languages: [LANGUAGES[0], LANGUAGES[1], LANGUAGES[7]],
    status: 'upcoming',
    delegateCount: 0,
    description: 'Best practices for adverse event monitoring and vaccine safety surveillance.',
  },
];

/** Mock glossary terms — vaccine/health terminology */
export const GLOSSARY_TERMS: GlossaryTerm[] = [
  {
    id: 'term-001',
    term: 'mRNA vaccine',
    category: 'immunology',
    translations: {
      fr: 'vaccin à ARNm',
      pt: 'vacina de mRNA',
      sw: 'chanjo ya mRNA',
      yo: 'àjẹsára mRNA',
      am: 'የmRNA ክትባት',
    },
    phonetic: 'em-ar-en-ay vak-seen',
    context: 'A type of vaccine that uses messenger RNA to instruct cells to produce a protein that triggers an immune response.',
    contributor: 'vacfa',
  },
  {
    id: 'term-002',
    term: 'Cold chain',
    category: 'logistics',
    translations: {
      fr: 'chaîne du froid',
      pt: 'cadeia de frio',
      sw: 'mfumo wa baridi',
      yo: 'ẹ̀wọ̀n ìtútù',
      am: 'የቀዝቃዛ ሰንሰለት',
    },
    phonetic: 'kohld chayn',
    context: 'Temperature-controlled supply chain for storing and transporting vaccines.',
    contributor: 'vacfa',
  },
  {
    id: 'term-003',
    term: 'Herd immunity',
    category: 'epidemiology',
    translations: {
      fr: 'immunité collective',
      pt: 'imunidade de rebanho',
      sw: 'kinga ya jamii',
      yo: 'àjẹ́sára àwùjọ',
      am: 'የመንጋ በሽታ መከላከያ',
    },
    phonetic: 'hurd ih-myoo-nuh-tee',
    context: 'When a sufficient proportion of a population is immune, providing indirect protection.',
    contributor: 'vacfa',
  },
  {
    id: 'term-004',
    term: 'Adjuvant',
    category: 'immunology',
    translations: {
      fr: 'adjuvant',
      pt: 'adjuvante',
      sw: 'kisaidizi cha chanjo',
      yo: 'olùrànlọ́wọ́ àjẹsára',
      am: 'ረዳት',
    },
    phonetic: 'aj-uh-vuhnt',
    context: 'A substance added to a vaccine to enhance the immune response.',
    contributor: 'vacfa',
  },
  {
    id: 'term-005',
    term: 'Seroconversion',
    category: 'immunology',
    translations: {
      fr: 'séroconversion',
      pt: 'soroconversão',
      sw: 'mabadiliko ya seramu',
      yo: 'ìyípadà sẹ́rọ̀',
      am: 'ሴሮኮንቨርሽን',
    },
    phonetic: 'seer-oh-kuhn-vur-zhuhn',
    context: 'The development of detectable antibodies in the blood following vaccination or infection.',
    contributor: 'vacfa',
  },
  {
    id: 'term-006',
    term: 'Booster dose',
    category: 'immunology',
    translations: {
      fr: 'dose de rappel',
      pt: 'dose de reforço',
      sw: 'dozi ya nyongeza',
      yo: 'ìwọ̀n àfikún',
      am: 'ማጠናከሪያ ክትባት',
    },
    phonetic: 'boo-ster dohs',
    context: 'An additional dose of vaccine given after the initial series to maintain immunity.',
    contributor: 'vacfa',
  },
  {
    id: 'term-007',
    term: 'Lyophilized',
    category: 'logistics',
    translations: {
      fr: 'lyophilisé',
      pt: 'liofilizado',
      sw: 'iliyokaushwa kwa baridi',
      yo: 'gbígbẹ ní ìtútù',
      am: 'በቀዝቃዛ የደረቀ',
    },
    phonetic: 'ly-off-uh-lyzd',
    context: 'Freeze-dried vaccine formulation that requires reconstitution before use.',
    contributor: 'vacfa',
  },
  {
    id: 'term-008',
    term: 'Pharmacovigilance',
    category: 'policy',
    translations: {
      fr: 'pharmacovigilance',
      pt: 'farmacovigilância',
      sw: 'uangalifu wa dawa',
      yo: 'ìṣọ́ra oògùn',
      am: 'የመድኃኒት ክትትል',
    },
    phonetic: 'far-muh-koh-vij-uh-luhns',
    context: 'The science of monitoring adverse effects of pharmaceutical products after market release.',
    contributor: 'organiser',
    contributorName: 'Dr. Fatima Diallo',
  },
  {
    id: 'term-009',
    term: 'Antigen',
    category: 'immunology',
    translations: {
      fr: 'antigène',
      pt: 'antígeno',
      sw: 'antijeni',
      yo: 'ohun-àjẹ́sára-ọ̀tá',
      am: 'አንቲጅን',
    },
    phonetic: 'an-tih-jen',
    context: 'A substance that triggers an immune response, especially the production of antibodies.',
    contributor: 'vacfa',
  },
  {
    id: 'term-010',
    term: 'Surveillance',
    category: 'epidemiology',
    translations: {
      fr: 'surveillance',
      pt: 'vigilância',
      sw: 'ufuatiliaji',
      yo: 'àbójútó',
      am: 'ክትትል',
    },
    phonetic: 'ser-vay-luhns',
    context: 'Systematic collection and analysis of health data to monitor disease trends.',
    contributor: 'vacfa',
  },
  {
    id: 'term-011',
    term: 'NITAG',
    category: 'policy',
    translations: {
      fr: 'NITAG (Comité consultatif technique national sur la vaccination - GTCV)',
      pt: 'NITAG (Comitê Técnico Assessor Nacional de Imunização)',
      sw: 'NITAG (Kamati ya Kitaifa ya Ushauri wa Kiufundi wa Chanjo)',
    },
    phonetic: 'ny-tag',
    context: 'National Immunization Technical Advisory Groups — independent expert technical groups that advise health ministries on evidence-based vaccine policies.',
    contributor: 'vacfa',
  },
  {
    id: 'term-011b',
    term: 'NISH',
    category: 'policy',
    translations: {
      fr: "NISH (Centre d'appui aux NITAG / Hub d'appui aux GTCV)",
      pt: 'NISH (Centro de Apoio aos NITAG)',
      sw: 'NISH (Kituo cha Usaidizi cha NITAG)',
    },
    phonetic: 'nish',
    context: 'NITAG Support Hub — hosted by VACFA at the University of Cape Town to provide technical assistance, evidence synthesis, and capacity building to National Immunization Technical Advisory Groups across Africa.',
    contributor: 'vacfa',
  },
  {
    id: 'term-012',
    term: 'RITAG',
    category: 'policy',
    translations: {
      fr: 'RITAG (Groupe consultatif technique régional sur la vaccination)',
      pt: 'RITAG (Grupo Consultivo Técnico Regional de Imunização)',
      sw: 'RITAG (Kikundi cha Ushauri wa Kiufundi wa Chanjo cha Kikanda)',
    },
    phonetic: 'ry-tag',
    context: 'Regional Immunization Technical Advisory Group guiding continental strategies for WHO Africa.',
    contributor: 'vacfa',
  },
  {
    id: 'term-013',
    term: 'EPI',
    category: 'policy',
    translations: {
      fr: 'PEV (Programme élargi de vaccination)',
      pt: 'PAV (Programa Alargado de Vacinação)',
      sw: 'EPI (Mpango Uliopanuliwa wa Chanjo)',
    },
    phonetic: 'ee-pee-eye',
    context: 'Expanded Programme on Immunization providing universal access to essential childhood vaccines.',
    contributor: 'vacfa',
  },
  {
    id: 'term-014',
    term: 'Gavi',
    category: 'policy',
    translations: {
      fr: "Gavi (l'Alliance du Vaccin)",
      pt: 'Gavi (Aliança Global de Vacinas)',
      sw: 'Gavi (Muungano wa Chanjo)',
    },
    phonetic: 'gah-vee',
    context: 'Gavi, the Vaccine Alliance — global public-private partnership increasing access to immunization.',
    contributor: 'vacfa',
  },
  {
    id: 'term-015',
    term: 'AEFI',
    category: 'epidemiology',
    translations: {
      fr: 'MAPI (Manifestations post-vaccinales indésirables)',
      pt: 'EAPV (Eventos Adversos Pós-Vacinação)',
      sw: 'AEFI (Matukio Mabaya Baada ya Chanjo)',
    },
    phonetic: 'ay-eff-ee',
    context: 'Adverse Events Following Immunization — any untoward medical occurrence following vaccine administration.',
    contributor: 'vacfa',
  },
  {
    id: 'term-016',
    term: 'Zero-dose children',
    category: 'epidemiology',
    translations: {
      fr: 'enfants zéro-dose',
      pt: 'crianças com dose zero',
      sw: 'watoto wasiopata chanjo yoyote',
    },
    phonetic: 'zee-roh dohs chil-druhn',
    context: 'Children who have not received a single dose of diphtheria-tetanus-pertussis (DTP1) vaccine.',
    contributor: 'vacfa',
  },
  {
    id: 'term-017',
    term: 'Cost-effectiveness analysis',
    category: 'policy',
    translations: {
      fr: 'analyse coût-efficacité (ACE)',
      pt: 'análise de custo-efetividade (ACE)',
      sw: 'uchambuzi wa gharama na ufanisi',
    },
    phonetic: 'kost ih-fek-tiv-nis uh-nal-uh-sis',
    context: 'Economic evaluation comparing the relative costs and outcomes (effects) of vaccine interventions.',
    contributor: 'vacfa',
  },
  {
    id: 'term-018',
    term: 'ICER',
    category: 'policy',
    translations: {
      fr: 'RCED (Ratio coût-efficacité différentiel)',
      pt: 'RCEI (Razão de custo-efetividade incremental)',
      sw: 'ICER (Uwiano wa gharama ya ziada kwa ufanisi)',
    },
    phonetic: 'eye-ser',
    context: 'Incremental Cost-Effectiveness Ratio — the economic summary measure representing economic value of an intervention.',
    contributor: 'vacfa',
  },
  {
    id: 'term-019',
    term: 'DALY',
    category: 'epidemiology',
    translations: {
      fr: "AVCI (Année de vie corrigée de l'incapacité - DALY)",
      pt: 'DALY (Anos de vida ajustados por incapacidade)',
      sw: 'DALY (Miaka ya maisha iliyorekebishwa kwa ulemavu)',
    },
    phonetic: 'dah-lee',
    context: 'Disability-Adjusted Life Year — a measure of overall disease burden expressed as cumulative years lost.',
    contributor: 'vacfa',
  },
  {
    id: 'term-020',
    term: 'VVM',
    category: 'logistics',
    translations: {
      fr: 'PCV (Pastille de contrôle du vaccin - VVM)',
      pt: 'MVV (Monitor de Frasco de Vacina)',
      sw: 'VVM (Kipima joto cha chupa ya chanjo)',
    },
    phonetic: 'vee-vee-em',
    context: 'Vaccine Vial Monitor — a thermal label registered on vaccine vials indicating cumulative heat exposure.',
    contributor: 'vacfa',
  },
  {
    id: 'term-021',
    term: 'Routine immunization',
    category: 'policy',
    translations: {
      fr: 'vaccination de routine',
      pt: 'imunização de rotina',
      sw: 'chanjo ya kawaida',
    },
    phonetic: 'roo-teen im-yuh-ny-zay-shun',
    context: 'Sustainable, scheduled provision of essential vaccines through standard primary health systems.',
    contributor: 'vacfa',
  },
  {
    id: 'term-022',
    term: 'Vaccine hesitancy',
    category: 'policy',
    translations: {
      fr: 'hésitation vaccinale',
      pt: 'hesitação vacinal',
      sw: 'kusitasita kwa chanjo',
    },
    phonetic: 'vak-seen hez-uh-tuhn-see',
    context: 'Delay in acceptance or refusal of vaccination despite availability of services.',
    contributor: 'vacfa',
  },
  {
    id: 'term-023',
    term: 'Budget impact analysis',
    category: 'policy',
    translations: {
      fr: "analyse d'impact budgétaire (AIB)",
      pt: 'análise de impacto orçamentário (AIO)',
      sw: 'uchambuzi wa athari za bajeti',
    },
    phonetic: 'buj-it im-pakt uh-nal-uh-sis',
    context: 'Economic evaluation assessing whether a health ministry can afford to introduce a new vaccine.',
    contributor: 'vacfa',
  },
  {
    id: 'term-024',
    term: 'Co-financing',
    category: 'policy',
    translations: {
      fr: 'co-financement national',
      pt: 'co-financiamento nacional',
      sw: 'ufadhili wa pamoja wa serikali',
    },
    phonetic: 'koh fy-nan-sing',
    context: 'National financial contribution share by recipient African governments towards Gavi-supported vaccines.',
    contributor: 'vacfa',
  },
  {
    id: 'term-025',
    term: 'Seroprevalence',
    category: 'epidemiology',
    translations: {
      fr: 'séroprévalence',
      pt: 'soroprevalência',
      sw: 'kuenea kwa seramu',
    },
    phonetic: 'seer-oh-prev-uh-luhns',
    context: 'The level of a pathogen in a population as measured in blood serum.',
    contributor: 'vacfa',
  },
  {
    id: 'term-026',
    term: 'Vaccine coverage',
    category: 'epidemiology',
    translations: {
      fr: 'couverture vaccinale',
      pt: 'cobertura vacinal',
      sw: 'kiwango cha chanjo',
    },
    phonetic: 'vak-seen kuhv-rij',
    context: 'The proportion of a target population that has received scheduled vaccine doses.',
    contributor: 'vacfa',
  },
  {
    id: 'term-027',
    term: 'Drop-out rate',
    category: 'epidemiology',
    translations: {
      fr: "taux d'abandon vaccinal",
      pt: 'taxa de abandono vacinal',
      sw: 'kiwango cha kuacha chanjo',
    },
    phonetic: 'drop owt rayt',
    context: 'Percentage of children who start an immunization schedule (e.g. DTP1) but fail to complete it (DTP3).',
    contributor: 'vacfa',
  },
  {
    id: 'term-028',
    term: 'Ultra-cold chain',
    category: 'logistics',
    translations: {
      fr: 'chaîne ultra-froide (-80°C)',
      pt: 'cadeia ultrafria (-80°C)',
      sw: 'mfumo wa baridi kali sana (-80°C)',
    },
    phonetic: 'uhl-truh kohld chayn',
    context: 'Extreme temperature-controlled storage environment (-80°C to -60°C) necessary for sensitive mRNA vaccines.',
    contributor: 'vacfa',
  },
  {
    id: 'term-029',
    term: 'Cost of illness',
    category: 'policy',
    translations: {
      fr: 'coût de la maladie (COI)',
      pt: 'custo da doença (COI)',
      sw: 'gharama ya ugonjwa',
    },
    phonetic: 'kost uhv il-nis',
    context: 'Economic evaluation measuring the total financial burden of a vaccine-preventable disease.',
    contributor: 'vacfa',
  },
  {
    id: 'term-030',
    term: 'Health Technology Assessment',
    category: 'policy',
    translations: {
      fr: 'évaluation des technologies de santé (ETS / HTA)',
      pt: 'avaliação de tecnologias em saúde (ATS / HTA)',
      sw: 'tathmini ya teknolojia ya afya (HTA)',
    },
    phonetic: 'helth tek-nol-uh-jee uh-ses-muhnt',
    context: 'Systematic evaluation of properties, effects, and impacts of health interventions to inform policy.',
    contributor: 'vacfa',
  },
  {
    id: 'term-031',
    term: 'SAHPRA',
    category: 'policy',
    translations: {
      fr: "SAHPRA (Autorité sud-africaine de réglementation des produits de santé)",
      pt: 'SAHPRA (Autoridade Reguladora de Produtos de Saúde da África do Sul)',
      sw: 'SAHPRA (Mamlaka ya Udhibiti wa Bidhaa za Afya ya Afrika Kusini)',
    },
    phonetic: 'sah-prah',
    context: 'South African Health Products Regulatory Authority — national medicines and health product regulator.',
    contributor: 'vacfa',
  },
  {
    id: 'term-032',
    term: 'SAGE',
    category: 'policy',
    translations: {
      fr: 'SAGE (Groupe stratégique consultatif d’experts sur la vaccination - OMS)',
      pt: 'SAGE (Grupo de Especialistas em Assessoria Estratégica em Imunização)',
      sw: 'SAGE (Kikundi cha Ushauri wa Kimkakati cha Wataalamu wa Chanjo)',
    },
    phonetic: 'sayj',
    context: 'Strategic Advisory Group of Experts on Immunization — principal advisory group to WHO for vaccines.',
    contributor: 'vacfa',
  },
  {
    id: 'term-033',
    term: 'AESI',
    category: 'epidemiology',
    translations: {
      fr: "EIIS (Événement indésirable d'intérêt particulier)",
      pt: 'EAEI (Eventos Adversos de Interesse Especial)',
      sw: 'AESI (Matukio Mabaya ya Maslahi Maalum)',
    },
    phonetic: 'ay-ee-es-eye',
    context: 'Adverse Events of Special Interest — pre-identified medical events with potential causal link to vaccines.',
    contributor: 'vacfa',
  },
  {
    id: 'term-034',
    term: 'CHW',
    category: 'logistics',
    translations: {
      fr: 'ASC (Agent de santé communautaire)',
      pt: 'ACS (Agente comunitário de saúde)',
      sw: 'CHW (Mhudumu wa afya ya jamii)',
    },
    phonetic: 'see-aych-duhb-yoo',
    context: 'Community Health Worker — frontline healthcare provider delivering immunization and primary care at community level.',
    contributor: 'vacfa',
  },
  {
    id: 'term-035',
    term: 'Reconstitution',
    category: 'logistics',
    translations: {
      fr: 'reconstitution du vaccin',
      pt: 'reconstituição da vacina',
      sw: 'uchanganyaji wa chanjo',
    },
    phonetic: 'ree-kon-stih-too-shun',
    context: 'The process of mixing a lyophilized (freeze-dried) vaccine with its specific liquid diluent before administration.',
    contributor: 'vacfa',
  },
  {
    id: 'term-036',
    term: 'Diluent',
    category: 'logistics',
    translations: {
      fr: 'diluant vaccinal',
      pt: 'diluente de vacina',
      sw: 'kimumunyishi cha chanjo',
    },
    phonetic: 'dil-yoo-uhnt',
    context: 'Liquid solvent provided by the manufacturer to dissolve freeze-dried vaccines before injection.',
    contributor: 'vacfa',
  },
  {
    id: 'term-037',
    term: 'Reach Every District (RED)',
    category: 'policy',
    translations: {
      fr: 'Approche Atteindre Chaque District (ACD)',
      pt: 'Alcançar Todos os Distritos (RED)',
      sw: 'Kufikia Kila Wilaya (RED)',
    },
    phonetic: 'reech ev-ree dis-trikt',
    context: 'WHO/UNICEF operational strategy to achieve 90% immunization coverage in all districts of African countries.',
    contributor: 'vacfa',
  },
  {
    id: 'term-038',
    term: 'Africa CDC',
    category: 'policy',
    translations: {
      fr: 'Centres africains de contrôle et de prévention des maladies (CDC Afrique)',
      pt: 'Centros de Controlo e Prevenção de Doenças de África (África CDC)',
      sw: 'Vituo vya Afrika vya Kudhibiti na Kuzuia Magonjwa (Afrika CDC)',
    },
    phonetic: 'af-rih-kuh see-dee-see',
    context: 'Autonomous public health agency of the African Union supporting member states in disease surveillance and outbreaks.',
    contributor: 'vacfa',
  },
  {
    id: 'term-039',
    term: 'Matric',
    category: 'policy',
    translations: {
      fr: 'baccalauréat / diplôme de fin d’études secondaires (Matric)',
      pt: 'certificado de conclusão do ensino secundário (Matric)',
      sw: 'cheti cha kumaliza masomo ya sekondari (Matric)',
    },
    phonetic: 'mah-trik',
    context: 'Final year of high school (Grade 12) and National Senior Certificate examination in South Africa.',
    contributor: 'vacfa',
  },
  {
    id: 'term-040',
    term: 'AEFI',
    category: 'epidemiology',
    translations: {
      fr: 'MAPI (Manifestations post-vaccinales indésirables)',
      pt: 'EAPV (Eventos Adversos Pós-Vacinação)',
      sw: 'AEFI (Matukio Mabaya Baada ya Chanjo)',
    },
    phonetic: 'ay-ee-ef-eye',
    context: 'Adverse Event Following Immunization — any untoward medical occurrence which follows immunization and which does not necessarily have a causal relationship with the usage of the vaccine.',
    contributor: 'vacfa',
  },
  {
    id: 'term-041',
    term: 'Signal detection',
    category: 'policy',
    translations: {
      fr: 'détection de signal',
      pt: 'deteção de sinais',
      sw: 'ugunduzi wa ishara',
    },
    phonetic: 'sig-nuhl dih-tek-shun',
    context: 'The active identification of new or changing safety information that may be associated with a vaccine.',
    contributor: 'vacfa',
  },
  {
    id: 'term-042',
    term: 'Anaphylaxis',
    category: 'immunology',
    translations: {
      fr: 'anaphylaxie',
      pt: 'anafilaxia',
      sw: 'mzio mkali',
    },
    phonetic: 'an-uh-fuh-lak-sis',
    context: 'A severe, potentially life-threatening systemic allergic reaction that can rarely occur post-vaccination.',
    contributor: 'vacfa',
  },
  {
    id: 'term-043',
    term: 'Causality assessment',
    category: 'epidemiology',
    translations: {
      fr: 'évaluation de la causalité',
      pt: 'avaliação de causalidade',
      sw: 'tathmini ya kisababishi',
    },
    phonetic: 'kaw-zal-ih-tee uh-ses-muhnt',
    context: 'The systematic scientific review of data on an AEFI to determine the likelihood that the vaccine caused the event.',
    contributor: 'vacfa',
  },
  {
    id: 'term-044',
    term: 'Multi-Dose Vial Policy (MDVP)',
    category: 'logistics',
    translations: {
      fr: 'politique des flacons multidoses (PFMD)',
      pt: 'política de frascos multidoses',
      sw: 'sera ya chupa za dozi nyingi (MDVP)',
    },
    phonetic: 'muhl-tee dohs vy-uhl pol-uh-see',
    context: 'WHO policy regarding the handling of opened multidose vials of vaccines for subsequent immunization sessions.',
    contributor: 'vacfa',
  },
  {
    id: 'term-045',
    term: 'Zero-dose children',
    category: 'epidemiology',
    translations: {
      fr: 'enfants zéro dose',
      pt: 'crianças dose zero',
      sw: 'watoto wasiopata dozi yoyote',
    },
    phonetic: 'zee-roh dohs chil-druhn',
    context: 'Children who have not received even a single dose of diphtheria, tetanus, and pertussis vaccine (DTP1).',
    contributor: 'vacfa',
  },
  {
    id: 'term-046',
    term: 'Shake test',
    category: 'logistics',
    translations: {
      fr: "test d'agitation",
      pt: 'teste de agitação',
      sw: 'jaribio la kutikisa',
    },
    phonetic: 'shayk test',
    context: 'Field physical test protocol to determine whether freeze-sensitive vaccines (e.g. DTP, HepB, TT) have been damaged by sub-zero temperatures.',
    contributor: 'vacfa',
  },
  {
    id: 'term-047',
    term: 'Neutralizing antibodies',
    category: 'immunology',
    translations: {
      fr: 'anticorps neutralisants',
      pt: 'anticorpos neutralizantes',
      sw: 'kingamwili za kuzuia',
    },
    phonetic: 'noo-truh-ly-zing an-tee-bod-eez',
    context: 'Antibodies that defend a cell from a pathogen or infectious particle by neutralizing any effect it has biologically.',
    contributor: 'vacfa',
  },
  {
    id: 'term-048',
    term: 'T-cell mediated immunity',
    category: 'immunology',
    translations: {
      fr: 'immunité à médiation cellulaire T',
      pt: 'imunidade mediada por células T',
      sw: 'kinga inayodhibitiwa na seli za T',
    },
    phonetic: 'tee-sel mee-dee-ay-tid ih-myoo-nih-tee',
    context: 'An immune response that does not involve antibodies, but rather the activation of phagocytes, antigen-specific cytotoxic T-lymphocytes.',
    contributor: 'vacfa',
  },
  {
    id: 'term-049',
    term: 'Breakthrough infection',
    category: 'epidemiology',
    translations: {
      fr: 'infection post-vaccinale',
      pt: 'infecção pós-vacinal',
      sw: 'maambukizi baada ya chanjo',
    },
    phonetic: 'brayk-throo in-fek-shun',
    context: 'Infection occurring in a person who is fully vaccinated against the target infectious disease.',
    contributor: 'vacfa',
  },
  {
    id: 'term-050',
    term: 'Maternal immunization',
    category: 'policy',
    translations: {
      fr: 'vaccination maternelle',
      pt: 'imunização materna',
      sw: 'chanjo kwa wajawazito',
    },
    phonetic: 'muh-tur-nuhl im-yuh-ny-zay-shun',
    context: 'Vaccination of pregnant women to induce maternal antibodies transferred across the placenta to protect the newborn infant.',
    contributor: 'vacfa',
  },
  {
    id: 'term-051',
    term: 'Correlates of protection',
    category: 'immunology',
    translations: {
      fr: 'corrélats de protection',
      pt: 'correlatos de proteção',
      sw: 'viashiria vya ulinzi',
    },
    phonetic: 'kor-uh-luhts uhv pruh-tek-shun',
    context: 'Measurable immune responses that correlate statistically with protection against clinical disease.',
    contributor: 'vacfa',
  },
  {
    id: 'term-052',
    term: 'Reactogenicity',
    category: 'immunology',
    translations: {
      fr: 'réactogénicité',
      pt: 'reatogenicidade',
      sw: 'athari za mara moja za chanjo',
    },
    phonetic: 'ree-ak-toh-juh-nis-ih-tee',
    context: 'Physical manifestation of the inflammatory response to vaccination, including local soreness, fever, or swelling.',
    contributor: 'vacfa',
  },
  {
    id: 'term-053',
    term: 'Immunogenicity',
    category: 'immunology',
    translations: {
      fr: 'immunogénicité',
      pt: 'imunogenicidade',
      sw: 'uwezo wa kuzalisha kinga',
    },
    phonetic: 'im-yuh-noh-juh-nis-ih-tee',
    context: 'The ability of a vaccine antigen to provoke an immune response in the human body.',
    contributor: 'vacfa',
  },
  {
    id: 'term-054',
    term: 'NITAG',
    category: 'policy',
    translations: {
      fr: 'CCVN (Comité consultatif national pour la vaccination)',
      pt: 'NITAG (Comité Técnico Assessor Nacional de Imunização)',
      sw: 'NITAG (Kamati ya Kitaifa ya Ushauri wa Kiufundi wa Chanjo)',
    },
    phonetic: 'nye-tag',
    context: 'National Immunization Technical Advisory Group — independent expert multidisciplinary body guiding national immunization policies.',
    contributor: 'vacfa',
  },
  {
    id: 'term-055',
    term: 'Missed opportunities for vaccination (MOV)',
    category: 'epidemiology',
    translations: {
      fr: 'opportunités manquées de vaccination (OMV)',
      pt: 'oportunidades perdidas de vacinação (OPV)',
      sw: 'fursa zilizokosekana za chanjo (MOV)',
    },
    phonetic: 'mist op-er-too-nih-teez',
    context: 'When an eligible person attends a health facility but does not receive the scheduled vaccine doses for which they qualify.',
    contributor: 'vacfa',
  },
  {
    id: 'term-056',
    term: 'Supplementary Immunization Activities (SIA)',
    category: 'policy',
    translations: {
      fr: 'activités de vaccination supplémentaire (AVS)',
      pt: 'actividades de imunização suplementar (AIS)',
      sw: 'shughuli za ziada za chanjo (SIA)',
    },
    phonetic: 'sup-luh-men-tuh-ree im-yuh-ny-zay-shun',
    context: 'Mass vaccination campaign targeting a specified age group in defined geographic areas regardless of previous vaccination history.',
    contributor: 'vacfa',
  },
  {
    id: 'term-057',
    term: 'Subunit vaccine',
    category: 'immunology',
    translations: {
      fr: 'vaccin sous-unitaire',
      pt: 'vacina de subunidade',
      sw: 'chanjo ya sehemu ya virusi',
    },
    phonetic: 'sub-yoo-nit vak-seen',
    context: 'Vaccine containing specific purified fragments (proteins or sugars) of the target pathogen rather than the whole microorganism.',
    contributor: 'vacfa',
  },
  {
    id: 'term-058',
    term: 'Conjugate vaccine',
    category: 'immunology',
    translations: {
      fr: 'vaccin conjugué',
      pt: 'vacina conjugada',
      sw: 'chanjo iliyounganishwa',
    },
    phonetic: 'kon-juh-git vak-seen',
    context: 'Vaccine created by linking a weak antigen polysaccharide to a strong protein carrier to induce robust T-cell response in infants.',
    contributor: 'vacfa',
  },
  {
    id: 'term-059',
    term: 'Toxoid',
    category: 'immunology',
    translations: {
      fr: 'anatoxine',
      pt: 'toxóide',
      sw: 'sumu iliyolemazwa (toxoid)',
    },
    phonetic: 'tok-soyd',
    context: 'Inactivated bacterial toxin that has lost toxicity but retains the capacity to stimulate formation of antitoxin antibodies (e.g. Tetanus).',
    contributor: 'vacfa',
  },
  {
    id: 'term-060',
    term: 'Wastage rate',
    category: 'logistics',
    translations: {
      fr: 'taux de perte de vaccins',
      pt: 'taxa de desperdício de vacinas',
      sw: 'kiwango cha upotevu wa chanjo',
    },
    phonetic: 'way-stij rayt',
    context: 'Percentage of vaccine doses supplied that are discarded unused, lost to expiry, or broken.',
    contributor: 'vacfa',
  },
  {
    id: 'term-061',
    term: 'Gavi',
    category: 'policy',
    translations: {
      fr: "Gavi, l'Alliance du Vaccin",
      pt: 'Gavi, a Aliança de Vacinas',
      sw: 'Gavi, Muungano wa Chanjo',
    },
    phonetic: 'gah-vee',
    context: 'Global Vaccine Alliance helping vaccinate more than half the world’s children against deadly infectious diseases.',
    contributor: 'vacfa',
  },
  {
    id: 'term-062',
    term: 'WHO AFRO',
    category: 'policy',
    translations: {
      fr: "Bureau régional de l'OMS pour l'Afrique (OMS AFRO)",
      pt: 'Escritório Regional da OMS para a África (OMS AFRO)',
      sw: 'Shirika la Afya Duniani Kanda ya Afrika (WHO AFRO)',
    },
    phonetic: 'doh-buhl-yoo aych oh af-roh',
    context: 'World Health Organization Regional Office for Africa serving 47 African Member States headquartered in Brazzaville.',
    contributor: 'vacfa',
  },
  {
    id: 'term-063',
    term: 'Xolie Ndlela',
    category: 'personnel',
    translations: {
      en: 'Xolie Ndlela',
      fr: 'Xolie Ndlela',
      pt: 'Xolie Ndlela',
      sw: 'Xolie Ndlela',
    },
    phonetic: 'zoh-lee un-dleh-lah',
    context: 'Administrative Officer & Core Team Member, Vaccines for Africa Initiative (VACFA), University of Cape Town.',
    contributor: 'vacfa',
  },
  {
    id: 'term-064',
    term: 'Edina Amponsah-Dacosta',
    category: 'personnel',
    translations: {
      en: 'Edina Amponsah-Dacosta',
      fr: 'Edina Amponsah-Dacosta',
      pt: 'Edina Amponsah-Dacosta',
      sw: 'Edina Amponsah-Dacosta',
    },
    phonetic: 'ee-dee-nah am-pohn-sah dah-koss-tah',
    context: 'Senior Research Officer & Vaccinologist, VACFA / School of Public Health and Family Medicine, University of Cape Town.',
    contributor: 'vacfa',
  },
  {
    id: 'term-065',
    term: 'Saleem Satardien',
    category: 'personnel',
    translations: {
      en: 'Saleem Satardien',
      fr: 'Saleem Satardien',
      pt: 'Saleem Satardien',
      sw: 'Saleem Satardien',
    },
    phonetic: 'sah-leem suh-tar-dee-en',
    context: 'Online Learning Environment Developer & Educational Technologist, VACFA and NISH, University of Cape Town.',
    contributor: 'vacfa',
  },
  {
    id: 'term-066',
    term: 'Alana Keyser',
    category: 'personnel',
    translations: {
      en: 'Alana Keyser',
      fr: 'Alana Keyser',
      pt: 'Alana Keyser',
      sw: 'Alana Keyser',
    },
    phonetic: 'uh-lah-nuh ky-zer',
    context: 'Project Manager, VACFA / Faculty of Health Sciences, University of Cape Town.',
    contributor: 'vacfa',
  },
  {
    id: 'term-067',
    term: 'Hilary Basson',
    category: 'personnel',
    translations: {
      en: 'Hilary Basson',
      fr: 'Hilary Basson',
      pt: 'Hilary Basson',
      sw: 'Hilary Basson',
    },
    phonetic: 'hil-uh-ree bah-sawn',
    context: 'Research Nurse & Clinical Coordinator, VACFA Immunization & Vaccine Clinical Studies, UCT.',
    contributor: 'vacfa',
  },
  {
    id: 'term-068',
    term: 'Benjamin Kagina',
    category: 'personnel',
    translations: {
      en: 'Benjamin Kagina',
      fr: 'Benjamin Kagina',
      pt: 'Benjamin Kagina',
      sw: 'Benjamin Kagina',
    },
    phonetic: 'ben-juh-min kuh-gee-nuh',
    context: 'Chief Research Officer & Associate Professor, Vaccines for Africa Initiative (VACFA), University of Cape Town.',
    contributor: 'vacfa',
  },
  {
    id: 'term-069',
    term: 'Gladstone Madito',
    category: 'personnel',
    translations: {
      en: 'Gladstone Madito',
      fr: 'Gladstone Madito',
      pt: 'Gladstone Madito',
      sw: 'Gladstone Madito',
    },
    phonetic: 'glad-stohn muh-dee-toh',
    context: 'Lecturer & Academic Faculty, Faculty of Health Sciences / VACFA, University of Cape Town.',
    contributor: 'vacfa',
  },
  {
    id: 'term-070',
    term: 'Liza Rossi',
    category: 'personnel',
    translations: {
      en: 'Liza Rossi',
      fr: 'Liza Rossi',
      pt: 'Liza Rossi',
      sw: 'Liza Rossi',
    },
    phonetic: 'lee-zah ross-ee',
    context: 'Research Officer, Timber Study (#TimberStudy) clinical research team / VACFA, University of Cape Town.',
    contributor: 'vacfa',
  },
  {
    id: 'term-071',
    term: 'Martie Abraham',
    category: 'personnel',
    translations: {
      en: 'Martie Abraham',
      fr: 'Martie Abraham',
      pt: 'Martie Abraham',
      sw: 'Martie Abraham',
    },
    phonetic: 'mar-tee ay-bruh-ham',
    context: 'Team Member & Professional Staff, VACFA / Faculty of Health Sciences, University of Cape Town.',
    contributor: 'vacfa',
  },
  {
    id: 'term-072',
    term: 'Gregory Hussey',
    category: 'personnel',
    translations: {
      en: 'Gregory Hussey',
      fr: 'Gregory Hussey',
      pt: 'Gregory Hussey',
      sw: 'Gregory Hussey',
    },
    phonetic: 'greg-uh-ree huss-ee',
    context: 'Senior Scholar & Emeritus Professor, Founding Director of VACFA, University of Cape Town.',
    contributor: 'vacfa',
  },
  {
    id: 'term-073',
    term: 'Petronella Ncube',
    category: 'personnel',
    translations: {
      en: 'Petronella Ncube',
      fr: 'Petronella Ncube',
      pt: 'Petronella Ncube',
      sw: 'Petronella Ncube',
    },
    phonetic: 'peh-troh-nel-uh en-koo-beh',
    context: 'Project Manager, VACFA / NISH (Network for Immunization Specialists) initiatives, University of Cape Town.',
    contributor: 'vacfa',
  },
  {
    id: 'term-074',
    term: 'Imen Ayouni Ep Labidi',
    category: 'personnel',
    translations: {
      en: 'Imen Ayouni Ep Labidi',
      fr: 'Imen Ayouni Ep Labidi',
      pt: 'Imen Ayouni Ep Labidi',
      sw: 'Imen Ayouni Ep Labidi',
    },
    phonetic: 'ee-men ah-yoo-nee ep lah-bee-dee',
    context: 'Team Member & Public Health Researcher, VACFA collaborative research group.',
    contributor: 'vacfa',
  },
  {
    id: 'term-075',
    term: 'Ramonde Patientia',
    category: 'personnel',
    translations: {
      en: 'Ramonde Patientia',
      fr: 'Ramonde Patientia',
      pt: 'Ramonde Patientia',
      sw: 'Ramonde Patientia',
    },
    phonetic: 'ruh-mawnd puh-ten-shuh',
    context: 'Senior Research Officer, VACFA / Department of Paediatrics and Child Health, University of Cape Town.',
    contributor: 'vacfa',
  },
  {
    id: 'term-076',
    term: 'Adelaide Masu',
    category: 'personnel',
    translations: {
      en: 'Adelaide Masu',
      fr: 'Adelaide Masu',
      pt: 'Adelaide Masu',
      sw: 'Adelaide Masu',
    },
    phonetic: 'ad-uh-layd mah-soo',
    context: 'Senior Lecturer & Academic Faculty, Faculty of Health Sciences / VACFA, University of Cape Town.',
    contributor: 'vacfa',
  },
  {
    id: 'term-077',
    term: 'Christine Ritchie',
    category: 'personnel',
    translations: {
      en: 'Christine Ritchie',
      fr: 'Christine Ritchie',
      pt: 'Christine Ritchie',
      sw: 'Christine Ritchie',
    },
    phonetic: 'kris-teen rih-chee',
    context: 'Project Manager, Timber Study (#TimberStudy) clinical trial & research operations / VACFA, UCT.',
    contributor: 'vacfa',
  },
  {
    id: 'term-078',
    term: 'Dilshaad Brey',
    category: 'personnel',
    translations: {
      en: 'Dilshaad Brey',
      fr: 'Dilshaad Brey',
      pt: 'Dilshaad Brey',
      sw: 'Dilshaad Brey',
    },
    phonetic: 'dil-shaad bray',
    context: 'Senior Librarian, Health Sciences Library & Information Specialist supporting VACFA systematic reviews, UCT.',
    contributor: 'vacfa',
  },
  {
    id: 'term-079',
    term: 'Nolitha',
    category: 'personnel',
    translations: {
      en: 'Nolitha',
      fr: 'Nolitha',
      pt: 'Nolitha',
      sw: 'Nolitha',
    },
    phonetic: 'noh-lee-tuh',
    context: 'Research Assistant, VACFA Clinical Research & Community Field Studies, University of Cape Town.',
    contributor: 'vacfa',
  },
  {
    id: 'term-080',
    term: 'Anthony Hawkridge',
    category: 'personnel',
    translations: {
      en: 'Anthony Hawkridge',
      fr: 'Anthony Hawkridge',
      pt: 'Anthony Hawkridge',
      sw: 'Anthony Hawkridge',
    },
    phonetic: 'an-thuh-nee hawk-rij',
    context: 'Senior Research Officer & Public Health Epidemiologist, VACFA / School of Public Health, UCT.',
    contributor: 'vacfa',
  },
  {
    id: 'term-081',
    term: 'Bronte Davies',
    category: 'personnel',
    translations: {
      en: 'Bronte Davies',
      fr: 'Bronte Davies',
      pt: 'Bronte Davies',
      sw: 'Bronte Davies',
    },
    phonetic: 'bron-tee day-veez',
    context: 'Junior Research Officer, VACFA / Faculty of Health Sciences, University of Cape Town.',
    contributor: 'vacfa',
  },
  {
    id: 'term-082',
    term: 'Marthe Penka',
    category: 'personnel',
    translations: {
      en: 'Marthe Penka',
      fr: 'Marthe Penka',
      pt: 'Marthe Penka',
      sw: 'Marthe Penka',
    },
    phonetic: 'mar-tuh pen-kuh',
    context: 'Team Member & Health Researcher, VACFA Francophone and Regional African public health projects.',
    contributor: 'vacfa',
  },
  {
    id: 'term-083',
    term: 'Elloise Du Toit',
    category: 'personnel',
    translations: {
      en: 'Elloise Du Toit',
      fr: 'Elloise Du Toit',
      pt: 'Elloise Du Toit',
      sw: 'Elloise Du Toit',
    },
    phonetic: 'el-wahz doo twah',
    context: 'Senior Research Officer, Division of Medical Microbiology & VACFA, University of Cape Town.',
    contributor: 'vacfa',
  },
  {
    id: 'term-084',
    term: 'Elizabeth Oduwole',
    category: 'personnel',
    translations: {
      en: 'Elizabeth Oduwole',
      fr: 'Elizabeth Oduwole',
      pt: 'Elizabeth Oduwole',
      sw: 'Elizabeth Oduwole',
    },
    phonetic: 'ih-liz-uh-buhth oh-doo-woh-lay',
    context: 'Research Officer & Evidence-Based Vaccinology Specialist, VACFA, University of Cape Town.',
    contributor: 'vacfa',
  },
  {
    id: 'term-085',
    term: 'Tshepiso Mbangiwa',
    category: 'personnel',
    translations: {
      en: 'Tshepiso Mbangiwa',
      fr: 'Tshepiso Mbangiwa',
      pt: 'Tshepiso Mbangiwa',
      sw: 'Tshepiso Mbangiwa',
    },
    phonetic: 'tseh-pee-soh um-bahn-gee-wah',
    context: 'Team Member & Researcher in Virology and Immunology, VACFA / University of Cape Town.',
    contributor: 'vacfa',
  },
  {
    id: 'term-086',
    term: 'Lubayna Khan',
    category: 'personnel',
    translations: {
      en: 'Lubayna Khan',
      fr: 'Lubayna Khan',
      pt: 'Lubayna Khan',
      sw: 'Lubayna Khan',
    },
    phonetic: 'loo-bay-nuh kahn',
    context: 'Research Assistant, VACFA Research Projects / Faculty of Health Sciences, University of Cape Town.',
    contributor: 'vacfa',
  },
  {
    id: 'term-087',
    term: 'Rudzani Muloiwa',
    category: 'personnel',
    translations: {
      en: 'Rudzani Muloiwa',
      fr: 'Rudzani Muloiwa',
      pt: 'Rudzani Muloiwa',
      sw: 'Rudzani Muloiwa',
    },
    phonetic: 'rood-zah-nee moo-loy-wah',
    context: 'Professor & Head of the Department of Paediatrics and Child Health, University of Cape Town; VACFA Co-Director & Steering Committee Member.',
    contributor: 'vacfa',
  },
  {
    id: 'term-088',
    term: 'Timber Study',
    category: 'epidemiology',
    translations: {
      fr: 'Étude Timber',
      pt: 'Estudo Timber',
      sw: 'Utafiti wa Timber',
    },
    phonetic: 'tim-ber stuh-dee',
    context: 'Clinical research and vaccine surveillance study protocol (#TimberStudy) conducted at VACFA / UCT.',
    contributor: 'vacfa',
  },
  {
    id: 'term-089',
    term: 'NISH 2.0',
    category: 'policy',
    translations: {
      fr: 'NISH 2.0 (Réseau des spécialistes de la vaccination)',
      pt: 'NISH 2.0 (Rede de Especialistas em Imunização)',
      sw: 'NISH 2.0 (Mtandao wa Wataalamu wa Chanjo)',
    },
    phonetic: 'neesh too pohynt zhee-roh',
    context: 'Network for Immunization Specialists second funding cycle / multi-country proposal to Wellcome and Gates Foundation; often misheard as "Niche".',
    contributor: 'vacfa',
  },
  {
    id: 'term-090',
    term: 'PICARD Fund',
    category: 'logistics',
    translations: {
      fr: 'Fonds PICARD',
      pt: 'Fundo PICARD',
      sw: 'Mfuko wa PICARD',
    },
    phonetic: 'pih-kard fund',
    context: 'Internal operational and project research account mechanism at UCT / VACFA used for unit administration and compliant business procurement.',
    contributor: 'vacfa',
  },
  {
    id: 'term-091',
    term: 'African Vaccinology Course (AVC)',
    category: 'policy',
    translations: {
      fr: 'Cours Africain de Vaccinologie (AVC)',
      pt: 'Curso Africano de Vacinologia (AVC)',
      sw: 'Kozi ya Kiafrika ya Taaluma ya Chanjo (AVC)',
    },
    phonetic: 'af-rih-kuhn vak-sih-nol-uh-jee kors',
    context: 'Flagship annual pan-African vaccinology training course convened by VACFA for immunization managers, medical officers, and researchers across Africa.',
    contributor: 'vacfa',
  },
  {
    id: 'term-092',
    term: 'TDEP Study',
    category: 'epidemiology',
    translations: {
      fr: 'Étude TDEP',
      pt: 'Estudo TDEP',
      sw: 'Utafiti wa TDEP',
    },
    phonetic: 'tee-dep stuh-dee',
    context: 'Clinical trial and household-based surveillance protocol evaluating Tdap / pertussis-tetanus-diphtheria immunization, approved by Sanofi Scientific Committee.',
    contributor: 'vacfa',
  },
  {
    id: 'term-093',
    term: 'TTAP Study',
    category: 'epidemiology',
    translations: {
      fr: 'Étude TTAP',
      pt: 'Estudo TTAP',
      sw: 'Utafiti wa TTAP',
    },
    phonetic: 'tee-tap stuh-dee',
    context: 'Scientific research study protocol at VACFA investigating vaccine immunology, serology, and antibody kinetics.',
    contributor: 'vacfa',
  },
  {
    id: 'term-094',
    term: 'VPOP Workshop',
    category: 'policy',
    translations: {
      fr: 'Atelier VPOP (Optimisation des politiques vaccinales)',
      pt: 'Oficina VPOP (Otimização de Políticas de Vacinas)',
      sw: 'Warsha ya VPOP (Uboreshaji wa Sera za Chanjo)',
    },
    phonetic: 'vee-pop wurk-shop',
    context: 'Vaccine Policy / Prioritization and Optimization Platform workshop in partnership with the Gates Foundation and WHO focusing on PCV and RSV immunization policy.',
    contributor: 'vacfa',
  },
  {
    id: 'term-095',
    term: 'NMAT',
    category: 'policy',
    translations: {
      fr: "NMAT (Outil d'évaluation de la maturité des NITAG)",
      pt: 'NMAT (Ferramenta de Avaliação de Maturidade de NITAG)',
      sw: 'NMAT (Zana ya Kutathmini Ukomavu wa NITAG)',
    },
    phonetic: 'en-mat',
    context: 'NITAG Maturity Assessment Tool — standardized evaluation framework deployed by WHO and Africa CDC to measure institutional capability of national immunization advisory bodies.',
    contributor: 'vacfa',
  },
  {
    id: 'term-096',
    term: 'PCV10 / PCV13 Formulations',
    category: 'immunology',
    translations: {
      fr: 'Formulations PCV10 / PCV13 (Vaccin antipneumococcique)',
      pt: 'Formulações PCV10 / PCV13 (Vacina pneumocócica)',
      sw: 'Fomula za PCV10 / PCV13 (Chanjo ya Nimonia)',
    },
    phonetic: 'pee-see-vee ten / thur-teen',
    context: 'Pneumococcal Conjugate Vaccine 10-valent and 13-valent formulations; economic and epidemiological modeling for vaccine switching in national programs (e.g. Mali NITAG).',
    contributor: 'vacfa',
  },
  {
    id: 'term-097',
    term: 'Respiratory Syncytial Virus (RSV)',
    category: 'immunology',
    translations: {
      fr: 'Virus Respiratoire Syncytial (VRS)',
      pt: 'Vírus Sincicial Respiratório (VSR)',
      sw: 'Virusi vya Kupumua vya Syncytial (RSV)',
    },
    phonetic: 'res-per-uh-tor-ee sin-sish-uhl vy-rus',
    context: 'High-priority viral respiratory pathogen causing acute infant bronchiolitis and pneumonia, targeted by maternal vaccines and monoclonal antibody interventions.',
    contributor: 'vacfa',
  },
  {
    id: 'term-098',
    term: 'MPACS (Mpox Case Study)',
    category: 'epidemiology',
    translations: {
      fr: 'Étude de cas Mpox (MPACS)',
      pt: 'Estudo de caso Mpox (MPACS)',
      sw: 'Uchunguzi wa kisa cha Mpox (MPACS)',
    },
    phonetic: 'em-paks',
    context: 'Mpox Preparedness and Outbreak Response case study developed for NITAG facilitation and Task Force for Global Health learning modules.',
    contributor: 'vacfa',
  },
  {
    id: 'term-099',
    term: 'HREC / HRAC',
    category: 'policy',
    translations: {
      fr: "Comité d'éthique de la recherche en santé (HREC)",
      pt: 'Comité de Ética em Pesquisa em Saúde (HREC)',
      sw: 'Kamati ya Maadili ya Utafiti wa Afya (HREC)',
    },
    phonetic: 'aych-rek / aych-rak',
    context: 'Health Research Ethics Committee at University of Cape Town Faculty of Health Sciences governing clinical trials, ethical approvals, and human participant clearance.',
    contributor: 'vacfa',
  },
  {
    id: 'term-100',
    term: 'MEL Framework',
    category: 'policy',
    translations: {
      fr: 'Cadre MEL (Suivi, Évaluation et Apprentissage)',
      pt: 'Quadro MEL (Monitorização, Avaliação e Aprendizagem)',
      sw: 'Mfumo wa MEL (Ufuatiliaji, Tathmini na Kujifunza)',
    },
    phonetic: 'em-ee-el fraym-wurk',
    context: 'Monitoring, Evaluation, and Learning framework used to measure research milestones, accountability, and project outcomes for international grants.',
    contributor: 'vacfa',
  },
  {
    id: 'term-101',
    term: 'Theory of Change',
    category: 'policy',
    translations: {
      fr: 'Théorie du changement',
      pt: 'Teoria da Mudança',
      sw: 'Nadharia ya Mabadiliko',
    },
    phonetic: 'thee-uh-ree uhv chaynj',
    context: 'Comprehensive methodological illustration explaining how project activities lead to sequential intermediate outcomes and final health policy impacts.',
    contributor: 'vacfa',
  },
  {
    id: 'term-102',
    term: 'Task Force for Global Health',
    category: 'policy',
    translations: {
      fr: 'Task Force pour la Santé Mondiale',
      pt: 'Task Force para a Saúde Global',
      sw: 'Kikosi Kazi cha Afya ya Ulimwengu',
    },
    phonetic: 'task fors for gloh-buhl helth',
    context: 'Non-profit international health alliance collaborating with US CDC and WHO on NITAG capacity building, case studies, and outbreak toolkits.',
    contributor: 'vacfa',
  },
  {
    id: 'term-103',
    term: 'Wellcome Trust',
    category: 'policy',
    translations: {
      fr: 'Wellcome Trust',
      pt: 'Wellcome Trust',
      sw: 'Wellcome Trust',
    },
    phonetic: 'wel-kuhm trust',
    context: 'Major global charitable biomedical research foundation funding NISH 2.0, vaccinology research, and health capacity grants across Africa.',
    contributor: 'vacfa',
  },
  {
    id: 'term-104',
    term: 'Gates Foundation',
    category: 'policy',
    translations: {
      fr: 'Fondation Bill & Melinda Gates',
      pt: 'Fundação Bill e Melinda Gates',
      sw: 'Taasisi ya Bill & Melinda Gates',
    },
    phonetic: 'gayts fown-day-shun',
    context: 'Bill & Melinda Gates Foundation — international philanthropic organization partnering with VACFA on VPOP workshops, immunization modeling, and polio/measles support.',
    contributor: 'vacfa',
  },
  {
    id: 'term-105',
    term: 'Funke Alaba',
    category: 'personnel',
    translations: {
      en: 'Funke Alaba',
      fr: 'Funke Alaba',
      pt: 'Funke Alaba',
      sw: 'Funke Alaba',
    },
    phonetic: 'foon-kay uh-lah-bah',
    context: 'Associate Professor & Health Economist, Health Economics Unit (HEU) / School of Public Health, UCT; collaborating with VACFA on Mali NITAG vaccine modeling.',
    contributor: 'vacfa',
  },
  {
    id: 'term-106',
    term: 'Richard White',
    category: 'personnel',
    translations: {
      en: 'Richard White',
      fr: 'Richard White',
      pt: 'Richard White',
      sw: 'Richard White',
    },
    phonetic: 'rich-erd wyt',
    context: 'Professor of Infectious Disease Modelling (London School of Hygiene & Tropical Medicine) and scientific webinar collaborator.',
    contributor: 'vacfa',
  },
  {
    id: 'term-107',
    term: 'Chepy (Tshepiso Mbangiwa)',
    category: 'personnel',
    translations: {
      en: 'Chepy',
      fr: 'Chepy',
      pt: 'Chepy',
      sw: 'Chepy',
    },
    phonetic: 'chep-ee',
    context: 'Familiar nickname for Tshepiso Mbangiwa used across VACFA meetings, referenced in connection with the TTAP and TDEP clinical studies.',
    contributor: 'vacfa',
  },
  {
    id: 'term-108',
    term: 'Polly (Petronella Ncube)',
    category: 'personnel',
    translations: {
      en: 'Polly',
      fr: 'Polly',
      pt: 'Polly',
      sw: 'Polly',
    },
    phonetic: 'pol-ee',
    context: 'Familiar nickname for Petronella Ncube within VACFA and NISH project management, MEL, and VPOP advisory logistics.',
    contributor: 'vacfa',
  },
  {
    id: 'term-109',
    term: 'Tony (Anthony Hawkridge)',
    category: 'personnel',
    translations: {
      en: 'Tony',
      fr: 'Tony',
      pt: 'Tony',
      sw: 'Tony',
    },
    phonetic: 'toh-nee',
    context: 'Familiar nickname for Dr. Anthony Hawkridge, Senior Research Officer leading NISH 2.0 writing and Timber webinar coordination.',
    contributor: 'vacfa',
  },
  {
    id: 'term-110',
    term: 'Employment Equity (EE)',
    category: 'policy',
    translations: {
      fr: "Équité en matière d'emploi (EE)",
      pt: 'Equidade de Emprego (EE)',
      sw: 'Usawa wa Ajira (EE)',
    },
    phonetic: 'em-ploy-muhnt ek-wih-tee',
    context: 'South African statutory policy framework and institutional demographic representation targets governing staff hiring, diversity, and disability declarations at UCT.',
    contributor: 'vacfa',
  },
  {
    id: 'term-111',
    term: 'Sanofi Scientific Committee',
    category: 'policy',
    translations: {
      fr: 'Comité Scientifique Sanofi',
      pt: 'Comité Científico da Sanofi',
      sw: 'Kamati ya Kisayansi ya Sanofi',
    },
    phonetic: 'suh-noh-fee sy-uhn-tif-ik kuh-mit-ee',
    context: 'Scientific evaluation body representing vaccine manufacturer Sanofi that evaluated and approved the TDEP study protocol for implementation.',
    contributor: 'vacfa',
  },
  {
    id: 'term-112',
    term: 'SPHFM',
    category: 'policy',
    translations: {
      fr: 'SPHFM (École de santé publique et de médecine familiale, UCT)',
      pt: 'SPHFM (Escola de Saúde Pública e Medicina Familiar, UCT)',
      sw: 'SPHFM (Shule ya Afya ya Umma na Dawa ya Familia, UCT)',
    },
    phonetic: 'es-pee-aych-ef-em',
    context: 'School of Public Health and Family Medicine at the University of Cape Town Faculty of Health Sciences, the academic faculty home of VACFA.',
    contributor: 'vacfa',
  },
];

/** Multilingual onboarding instruction caption for new sessions */
export const INITIAL_INSTRUCTION_CAPTION: CaptionEntry = {
  id: 'instruction-001',
  speaker: 'VACFA Conference System',
  timestamp: 'Live',
  originalText: 'Welcome to the session. Please select your audio channel on the right and click Listen to unmute. Choose your preferred language for real-time captions.',
  translations: {
    en: 'Welcome to the session. Please select your audio channel on the right and click Listen to unmute. Choose your preferred language for real-time captions.',
    fr: 'Bienvenue à la session. Veuillez sélectionner votre canal audio sur la droite et cliquer sur Écouter pour activer le son. Choisissez votre langue pour les sous-titres en direct.',
    pt: 'Bem-vindo à sessão. Selecione o seu canal de áudio à direita e clique em Ouvir para ativar o som. Escolha o seu idioma preferido para legendas em tempo real.',
    sw: 'Karibu kwenye kipindi. Tafadhali chagua kituo chako cha sauti upande wa kulia na ubofye Sikiliza ili kuwasha sauti. Chagua lugha unayopendelea kwa manukuu ya moja kwa moja.',
    yo: 'Ẹ káàbọ̀ sí ìpàdé yìí. Jọ̀wọ́ yan ibi ìgbọ́rọ̀ rẹ ní apá ọ̀tún kí o tẹ Gbọ́ láti ṣí ohùn. Yan èdè tí o fẹ́ fún àwọn àkọlé lásìkò gangan.',
    zu: 'Siyakwamukela kulesi seshini. Sicela ukhethe isiteshi sakho somsindo kwesokudla bese uchofoza u-Lalela ukuvula umsindo. Khetha ulimi oluthandayo lwemibhalo engezansi yesikhathi sangempela.',
    am: 'ወደ ስብሰባው በደህና መጡ። እባክዎ በቀኝ በኩል ያለውን የኦዲዮ ቻናል ይምረጡና ድምፁን ለማብራት ማዳመጥ የሚለውን ይጫኑ። ለቀጥታ የትርጉም ጽሑፍ የመረጡትን ቋንቋ ይምረጡ።',
    ha: 'Barka da zuwa wannan zama. Da fatan za a zaɓi tashar sauti a hannun dama kuma danna Saurara don kunna sauti. Zaɓi yaren da kuka fi so don fassarar rubutu ta kai tsaye.',
  },
  glossaryTerms: [],
};

/** Simulated live caption transcript for a vaccine conference */
export const DEMO_CAPTIONS: CaptionEntry[] = [
  INITIAL_INSTRUCTION_CAPTION,
  {
    id: 'cap-002',
    speaker: 'Dr. Amina Osei',
    timestamp: '09:00:28',
    originalText: 'Today we will be discussing the latest developments in mRNA vaccine technology and its deployment across Sub-Saharan Africa.',
    translations: {
      fr: `Aujourd'hui, nous allons discuter des derniers développements de la technologie des vaccins à ARNm et de son déploiement en Afrique subsaharienne.`,
      pt: `Hoje discutiremos os últimos desenvolvimentos da tecnologia de vacinas de mRNA e sua implantação na África Subsaariana.`,
      sw: `Leo tutajadili maendeleo ya hivi punde katika teknolojia ya chanjo ya mRNA na usambazaji wake kote katika Kusini mwa Jangwa la Sahara.`
    },
    glossaryTerms: ['mRNA vaccine'],
  },
  {
    id: 'cap-003',
    speaker: 'Dr. Amina Osei',
    timestamp: '09:00:51',
    originalText: 'As many of you know, maintaining the cold chain has been one of our greatest challenges in reaching rural communities.',
    translations: {
      fr: `Comme beaucoup d'entre vous le savent, le maintien de la chaîne du froid a été l'un de nos plus grands défis pour atteindre les communautés rurales.`,
      pt: `Como muitos de vocês sabem, manter a cadeia de frio tem sido um dos nossos maiores desafios para alcançar as comunidades rurais.`,
      sw: `Kama wengi wenu mnavyojua, kudumisha mfumo wa baridi imekuwa moja ya changamoto zetu kubwa katika kufikia jamii za vijijini.`
    },
    glossaryTerms: ['Cold chain'],
  },
  {
    id: 'cap-004',
    speaker: 'Prof. Kwame Asante',
    timestamp: '09:01:15',
    originalText: 'Thank you, Dr. Osei. I would like to present our findings on seroconversion rates following the booster dose campaigns in West Africa.',
    translations: {
      fr: `Merci, Dr Osei. Je voudrais présenter nos résultats sur les taux de séroconversion suite aux campagnes de dose de rappel en Afrique de l'Ouest.`,
      pt: `Obrigado, Dra. Osei. Gostaria de apresentar nossas descobertas sobre as taxas de soroconversão após as campanhas de dose de reforço na África Ocidental.`,
      sw: `Asante, Dkt. Osei. Ningependa kuwasilisha matokeo yetu kuhusu viwango vya mabadiliko ya seramu kufuatia kampeni za dozi ya nyongeza huko Afrika Magharibi.`
    },
    glossaryTerms: ['seroconversion', 'booster dose'],
  },
  {
    id: 'cap-005',
    speaker: 'Prof. Kwame Asante',
    timestamp: '09:01:38',
    originalText: 'Our data shows that the lyophilized formulations performed exceptionally well in high-temperature environments, reducing dependency on traditional cold chain infrastructure.',
    translations: {
      fr: 'Nos données montrent que les formulations lyophilisées ont exceptionnellement bien fonctionné dans des environnements à haute température, réduisant la dépendance aux infrastructures traditionnelles de chaîne du froid.',
      pt: `Nossos dados mostram que as formulações liofilizadas tiveram um desempenho excepcionalmente bom em ambientes de alta temperatura, reduzindo a dependência da infraestrutura tradicional da cadeia de frio.`,
      sw: `Takwimu zetu zinaonyesha kuwa michanganyiko iliyokaushwa kwa baridi ilifanya vizuri sana katika mazingira ya joto la juu, na kupunguza utegemezi wa miundombinu ya jadi ya mfumo wa baridi.`
    },
    glossaryTerms: ['lyophilized', 'cold chain'],
  },
  {
    id: 'cap-006',
    speaker: 'Prof. Kwame Asante',
    timestamp: '09:02:05',
    originalText: 'The adjuvant we used in the trial significantly enhanced the immune response, particularly in populations with prior exposure.',
    translations: {
      fr: `L'adjuvant que nous avons utilisé dans l'essai a considérablement amélioré la réponse immunitaire, en particulier dans les populations avec une exposition antérieure.`,
      pt: `O adjuvante que usamos no ensaio melhorou significativamente a resposta imune, particularmente em populações com exposição prévia.`,
      sw: `Kisaidizi cha chanjo tulichotumia katika jaribio kiliongeza kwa kiasi kikubwa majibu ya kinga, hasa katika makundi yenye mfiduo wa awali.`
    },
    glossaryTerms: ['adjuvant'],
  },
  {
    id: 'cap-007',
    speaker: 'Dr. Fatima Diallo',
    timestamp: '09:02:30',
    originalText: 'I want to emphasize the importance of pharmacovigilance in these campaigns. We need robust surveillance systems to monitor adverse events.',
    translations: {
      fr: `Je veux souligner l'importance de la pharmacovigilance dans ces campagnes. Nous avons besoin de systèmes de surveillance robustes pour surveiller les événements indésirables.`,
      pt: `Quero enfatizar a importância da farmacovigilância nessas campanhas. Precisamos de sistemas de vigilância robustos para monitorar eventos adversos.`,
      sw: `Ninataka kusisitiza umuhimu wa uangalifu wa dawa katika kampeni hizi. Tunahitaji mifumo imara ya ufuatiliaji ili kufuatilia matukio mabaya.`
    },
    glossaryTerms: ['pharmacovigilance', 'surveillance'],
  },
  {
    id: 'cap-008',
    speaker: 'Dr. Fatima Diallo',
    timestamp: '09:02:52',
    originalText: 'The antigen stability data from Mozambique and Angola have been very encouraging for the Portuguese-speaking regions.',
    translations: {
      fr: `Les données de stabilité des antigènes du Mozambique et de l'Angola ont été très encourageantes pour les régions lusophones.`,
      pt: `Os dados de estabilidade do antígeno de Moçambique e Angola têm sido muito animadores para as regiões de língua portuguesa.`,
      sw: `Takwimu za uthabiti wa antijeni kutoka Msumbiji na Angola zimekuwa zikitia moyo sana kwa mikoa inayozungumza Kireno.`
    },
    glossaryTerms: ['antigen'],
  },
  {
    id: 'cap-009',
    speaker: 'Dr. Amina Osei',
    timestamp: '09:03:18',
    originalText: 'Achieving herd immunity across the continent requires coordinated efforts between all national immunization programs.',
    translations: {
      fr: `Atteindre l'immunité collective à travers le continent nécessite des efforts coordonnés entre tous les programmes nationaux de vaccination.`,
      pt: `Alcançar a imunidade de rebanho em todo o continente requer esforços coordenados entre todos os programas nacionais de imunização.`,
      sw: `Kufikia kinga ya jamii kote barani kunahitaji juhudi za pamoja kati ya programu zote za kitaifa za chanjo.`
    },
    glossaryTerms: ['herd immunity'],
  },
  {
    id: 'cap-010',
    speaker: 'Dr. Amina Osei',
    timestamp: '09:03:45',
    originalText: 'Let us now hear from our regional coordinators about the progress in their respective areas.',
    translations: {
      fr: 'Écoutons maintenant nos coordinateurs régionaux sur les progrès réalisés dans leurs domaines respectifs.',
      pt: 'Vamos agora ouvir nossos coordenadores regionais sobre o progresso em suas respectivas áreas.',
      sw: 'Sasa tusikilize kutoka kwa waratibu wetu wa mikoa kuhusu maendeleo katika maeneo yao.'
    },
    glossaryTerms: [],
  },
];

/** Active translation channels for the live session view */
export const TRANSLATION_CHANNELS: TranslationChannel[] = [
  { language: LANGUAGES[0], listenerCount: 0, health: 'healthy', latencyMs: 145 },
  { language: LANGUAGES[1], listenerCount: 0, health: 'healthy', latencyMs: 180 },
  { language: LANGUAGES[2], listenerCount: 0, health: 'healthy', latencyMs: 210 },
  { language: LANGUAGES[3], listenerCount: 0, health: 'healthy', latencyMs: 450 },
  { language: LANGUAGES[4], listenerCount: 0, health: 'healthy', latencyMs: 195 },
  { language: LANGUAGES[6], listenerCount: 0, health: 'healthy', latencyMs: 220 },
  { language: LANGUAGES[7], listenerCount: 0, health: 'offline', latencyMs: 0 },
];

/** Dashboard statistics */
export const DASHBOARD_STATS: DashboardStats = {
  activeSessions: 1,
  totalDelegates: 347,
  activeLanguages: 6,
  glossaryTerms: GLOSSARY_TERMS.length,
};

/** Activity feed entries */
export const ACTIVITY_FEED: ActivityEntry[] = [
  {
    id: 'act-001',
    type: 'session_started',
    description: 'GAVI Immunization Summit 2026 is now live',
    timestamp: '2026-08-15T09:00:00Z',
    user: 'Dr. Amina Osei',
  },
  {
    id: 'act-002',
    type: 'glossary_updated',
    description: 'Added "Pharmacovigilance" to the glossary',
    timestamp: '2026-08-14T16:30:00Z',
    user: 'Dr. Fatima Diallo',
  },
  {
    id: 'act-003',
    type: 'session_ended',
    description: 'mRNA Vaccine Rollout: Lessons from Africa has ended',
    timestamp: '2026-08-14T12:45:00Z',
    user: 'System',
  },
  {
    id: 'act-004',
    type: 'organiser_added',
    description: 'Prof. Kwame Asante added as organiser',
    timestamp: '2026-08-13T10:00:00Z',
    user: 'Admin',
  },
  {
    id: 'act-005',
    type: 'session_created',
    description: 'NITAG Strengthening Forum scheduled for Aug 20',
    timestamp: '2026-08-12T14:20:00Z',
    user: 'Dr. Amina Osei',
  },
  {
    id: 'act-006',
    type: 'glossary_updated',
    description: 'Updated French translations for 3 terms',
    timestamp: '2026-08-11T09:15:00Z',
    user: 'Admin',
  },
];

/** Sidebar navigation items for the admin dashboard */
export const ADMIN_NAV_ITEMS: NavItem[] = [
  { id: 'overview', label: 'Overview', icon: 'home', href: '/dashboard' },
  { id: 'sessions', label: 'Sessions', icon: 'mic', href: '/dashboard/sessions', badge: '1 Live' },
  { id: 'glossary', label: 'Glossary', icon: 'book-open', href: '/dashboard/glossary', badge: GLOSSARY_TERMS.length },
  { id: 'organisers', label: 'Organisers', icon: 'users', href: '/dashboard/organisers' },
  { id: 'settings', label: 'Settings', icon: 'settings', href: '/dashboard/settings' },
];

export const GLOSSARY_CATEGORIES = {
  immunology: { label: 'Immunology', color: '#C41E3A' },
  epidemiology: { label: 'Epidemiology', color: '#FF9800' },
  logistics: { label: 'Logistics', color: '#4CAF50' },
  policy: { label: 'Policy', color: '#2196F3' },
  personnel: { label: 'Faculty & Team', color: '#9C27B0' },
} as const;
